# -*- coding: utf-8 -*-
"""Copy of password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl-01wBk1lsYmjKs0dWLre-mJLSIcgEK
"""

import random
import string
print("Laberies imported successful")

print("letters:", string.ascii_letters)
print("digit:", string.digits)
print("symbols:", string.punctuation)

characters = string.ascii_letters +  string.digits  + string.punctuation
print("All characters combine:")
print(characters)
print("Total characters:", len(characters))
def generate_password(length):
  characters = string.ascii_letters +  string.digits  + string.punctuation

  password = ""
  for i in range(length):
    password  += random.choice(characters)
  return password

# print("8 character password:", generate_password(8))
# print("12 character password:", generate_password(12))
# print("16 character password:", generate_password(16))

try:
  length = int(input("Enter the length of choice:"))
  count = int(input("How many passwords do you want?"))
  if length < 6:
    print("password is too short! minimun should be 6")
  else:
    print(f"\n Your {count} passwords:")
    print("_" * 30)
    for i in range(count):
        password = generate_password(length)
        print(f"{i+1}. {password}")
    print("_" * 30)

    # print(f"Your pasword is: {password}")
except ValueError:
  print("enter a valid digit")